import smtplib
import os
import datetime
from dotenv import load_dotenv # <--- ADDED THIS TO READ .ENV
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
from reportlab.lib import colors

# Load environment variables
load_dotenv()

def generate_pdf_proposal(responses):
    """
    Generates a professional, formatted PDF report using Platypus.
    responses: List of tuples (Requirement, Answer)
    """
    # 1. Setup File Name with Timestamp
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"BidWiz_Proposal_{timestamp}.pdf"
    
    # 2. Setup the Document Canvas
    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=18
    )

    # 3. Define Professional Styles
    styles = getSampleStyleSheet()
    
    # Title Style
    styles.add(ParagraphStyle(name='MainTitle', parent=styles['Heading1'], 
                              fontSize=24, color=colors.darkblue, spaceAfter=20, alignment=TA_LEFT))
    
    # Question Header Style
    styles.add(ParagraphStyle(name='Q_Header', parent=styles['Heading2'], 
                              fontSize=12, color=colors.darkblue, spaceBefore=15, spaceAfter=5))
    
    # Answer Body Style
    styles.add(ParagraphStyle(name='A_Body', parent=styles['Normal'], 
                              fontSize=10, leading=14, alignment=TA_JUSTIFY))

    # Confidential Footer Style
    styles.add(ParagraphStyle(name='Footer', parent=styles['Normal'], 
                              fontSize=8, color=colors.grey, alignment=TA_LEFT))

    # 4. Build the Content Flow
    Story = []

    # -- Cover Section --
    Story.append(Paragraph("Strategic Proposal Response", styles['MainTitle']))
    Story.append(Paragraph(f"Generated by BidWiz AI Agent", styles['Heading3']))
    Story.append(Paragraph(f"Date: {datetime.datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    Story.append(Spacer(1, 12))
    Story.append(Paragraph("CONFIDENTIAL DOCUMENT", styles['Footer']))
    Story.append(Spacer(1, 30))
    Story.append(Paragraph("Executive Summary of Requirements", styles['Heading2']))
    Story.append(Spacer(1, 12))

    # -- Loop Through Q&A --
    for req, ans in responses:
        # The Question (Bold & Blue)
        # We sanitize the text to prevent XML parsing errors in ReportLab
        clean_req = str(req).replace('<', '&lt;').replace('>', '&gt;').replace('\n', '<br/>')
        Story.append(Paragraph(f"<b>REQUIREMENT:</b> {clean_req}", styles['Q_Header']))
        
        # The Answer (Standard Text)
        clean_ans = str(ans).replace('<', '&lt;').replace('>', '&gt;').replace('\n', '<br/>')
        Story.append(Paragraph(clean_ans, styles['A_Body']))
        
        # Add spacing between items
        Story.append(Spacer(1, 20))

    # -- End of Report Marker --
    Story.append(Spacer(1, 30))
    Story.append(Paragraph("--- End of Automated Generation ---", styles['Footer']))

    # 5. Build PDF
    doc.build(Story)
    
    return filename

def send_email_with_attachment(recipient_email, pdf_filename):
    """
    Sends the generated PDF via SMTP.
    """
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")

    if not sender_email or not sender_password:
        return "Error: Email credentials missing in .env"

    msg = MIMEMultipart()
    # Intelligent Subject Line
    msg['Subject'] = f"Action Required: Proposal Draft {pdf_filename}"
    msg['From'] = sender_email
    msg['To'] = recipient_email

    # Professional Email Body
    body = f"""
    Hello,

    The BidWiz Autonomous Agent has completed the draft response for the recent RFP requirements.
    
    ATTACHMENT: {pdf_filename}
    STATUS: Ready for Human Review
    
    Please review the attached PDF document. The 'Critic Agent' has already verified the content for basic compliance.
    
    Regards,
    BidWiz Automation Engine
    """
    
    msg.attach(MIMEText(body, 'plain'))

    # Attach PDF
    try:
        with open(pdf_filename, "rb") as f:
            attach = MIMEApplication(f.read(), _subtype="pdf")
            attach.add_header('Content-Disposition', 'attachment', filename=pdf_filename)
            msg.attach(attach)
        
        # SMTP Session
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
            
        return "Email Sent Successfully"
    except Exception as e:
        return f"SMTP Error: {str(e)}"